### ISSUE TITLE
Trouble with finding executable file

### ISSUE THREAD

**Issue by ms1ms1** [pkmital/KinectHandAnalysis#1]
Hello. I am a new user of linux and c. I know this sounds dumb, but I cannot find a way to execute the program you published.

**Comment by pkmital** [comment]
There isn't one really, it is more the source code release and it depends on openFrameworks and some other libraries... but it is a pretty old project and unlikely to compile anymore!  More kept here as a reference.  If you are interested in doing hand analysis using this technique, I'd recommend checking out OpenCV!
